# Job Filtering Configuration
job_filters:
  # Allowed locations (case-insensitive partial matches)
  allowed_locations:
    - "India"
    - "Hyderabad"
    - "Bangalore"
    - "Mumbai"
    - "Delhi"
    - "Remote"
    - "Work from home"
  
  # Required skills (at least one must be present)
  required_skills:
    - "python"
    - "machine learning"
    - "ml"
    - "data science"
    - "nlp"
    - "natural language processing"
    - "deep learning"
    - "ai"
    - "artificial intelligence"
    - "data engineering"
    - "software engineering"
    - "web development"
    - "full stack"
    - "backend"
    - "frontend"
  
  # Excluded seniority levels
  excluded_seniority:
    - "director"
    - "vp"
    - "c-level"
    - "executive"
  
  # Preferred seniority (if specified, only these will be included)
  preferred_seniority:
    - "fresher"
    - "junior"
    - "mid"
    - "senior"

# Posting Configuration
posting:
  # Platforms to post to
  platforms:
    - "linkedin"
  
  # Posting schedule (24-hour format, Asia/Kolkata timezone)
  schedule:
    linkedin:
      - "09:00"
      - "18:00"
  
  # Maximum posts per day per platform
  max_posts_per_day:
    linkedin: 4
  
  # Caption generation preferences
  captions:
    linkedin:
      max_length: 1300
      hashtag_count: 4
      tone: "professional"
      audience: "Indian tech professionals"

# Job Sources Configuration
job_sources:
  # RapidAPI endpoints
  rapidapi:
    enabled: true
    indeed:
      enabled: true
      max_results: 100
      keywords: ["python developer", "machine learning engineer", "data scientist"]
    
    naukri:
      enabled: true
      max_results: 100
      keywords: ["python", "ml", "data science"]
    
    linkedin_jobs:
      enabled: true
      max_results: 100
      keywords: ["python", "machine learning", "data science"]
  
  # Job aggregators
  aggregators:
    jooble:
      enabled: true
      max_results: 200
      keywords: ["python", "machine learning", "ml", "data science", "nlp", "natural language processing", "deep learning", "ai", "artificial intelligence", "data engineering", "software engineering", "web development", "full stack", "backend", "frontend"]

# Database Configuration
database:
  # Use MongoDB for primary data store
  type: "mongodb"
  mongodb:
    uri: "mongodb+srv://karanraj3056:KL3ARGzj5BrUrzeP@jobauto.9xnjqy4.mongodb.net/?retryWrites=true&w=majority&appName=Jobauto"
    database: "Job_auto"

# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file: "logs/job_automation.log"
  max_size: "10 MB"
  retention: "30 days"

# LLM Configuration - Gemini
llm:
  provider: "gemini"
  model: "gemini-pro"
  max_tokens: 150
  temperature: 0.7
  caption_style: "professional"
  emoji_enabled: true
  hashtag_count: 3

# Image Generation Configuration
image_generation:
  enabled: true
  provider: "gemini"
  model: "gemini-pro-vision"
  style: "professional"
  size: "1024x1024"
  include_logo: true
  include_job_title: true
  include_company_name: true
  background_style: "clean"
