
# Job Filtering Configuration
job_filters:
  # Allowed locations (case-insensitive partial matches)
  allowed_locations:
    - "India"
    - "Hyderabad"
    - "Bangalore"
    - "Mumbai"
    - "Delhi"
    - "Remote"
    - "Work from home"
  
  # Required skills (at least one must be present)
  required_skills:
    - "python"
    - "machine learning"
    - "ml"
    - "data science"
    - "nlp"
    - "natural language processing"
    - "deep learning"
    - "ai"
    - "artificial intelligence"
    - "data engineering"
    - "software engineering"
    - "web development"
    - "full stack"
    - "backend"
    - "frontend"
  
  # Excluded seniority levels (exclude all senior positions)
  excluded_seniority:
    - "director"
    - "vp"
    - "c-level"
    - "executive"
    - "senior"
    - "lead"
    - "principal"
    - "architect"
    - "manager"
    - "head"
    - "chief"
    - "staff"
    - "senior developer"
    - "senior engineer"
    - "senior analyst"
    - "senior scientist"
    - "senior consultant"
    - "team lead"
    - "tech lead"
    - "engineering manager"
  
  # Preferred seniority (only include entry-level positions)
  preferred_seniority:
    - "fresher"
    - "junior"
    - "graduates"
    - "entry level"
    - "entry-level"
    - "0-1 years"
    - "0-2 years"
    - "1-2 years"
    - "1+ years"
    - "2+ years"
    - "new grad"
    - "new graduate"
    - "recent graduate"
    - "student"
    - "intern"
    - "internship"
    - "trainee"
    - "associate"
    - "assistant"

# Posting Configuration
posting:
  # Platforms to post to
  platforms:
    - "linkedin"
  
  # Posting schedule (24-hour format, Asia/Kolkata timezone)
  schedule:
    linkedin:
      - "09:00"
      - "18:00"
  
  # Maximum posts per day per platform
  max_posts_per_day:
    linkedin: 4
  
  # Caption generation preferences
  captions:
    linkedin:
      max_length: 3000
      hashtag_count: 7
      tone: "professional"
      audience: "Indian tech professionals"

# Job Sources Configuration
job_sources:
  # RapidAPI endpoints
  rapidapi:
    enabled: true
    indeed:
      enabled: true
      max_results: 50
      keywords: ["python developer", "machine learning engineer", "data scientist", "software engineer", "data analyst", "frontend developer", "backend developer", "full stack developer", "mern stack developer", "python", "ml engineer", "data engineer", "web developer", "react developer", "node.js developer", "java developer"]

    naukri:
      enabled: true
      max_results: 50
      keywords: ["python developer", "machine learning engineer", "data scientist", "software engineer", "data analyst", "frontend developer", "backend developer", "full stack developer", "mern stack developer", "python", "ml engineer", "data engineer", "web developer", "react developer", "node.js developer", "java developer"]

    
    linkedin_jobs:
      enabled: true
      max_results: 50
      keywords: ["python developer", "machine learning engineer", "data scientist", "software engineer", "data analyst", "frontend developer", "backend developer", "full stack developer", "mern stack developer", "python", "ml engineer", "data engineer", "web developer", "react developer", "node.js developer", "java developer"]
  
  # Job aggregators
  aggregators:
    jooble:
      enabled: true
      max_results: 50
      keywords: ["python", "machine learning", "ml", "data science", "nlp", "natural language processing", "deep learning", "ai", "artificial intelligence", "data engineering", "software engineering", "web development", "full stack", "backend", "frontend", "react", "node.js", "java", "javascript", "typescript"]

# Database Configuration
database:
  # Use MongoDB for primary data store
  type: "mongodb"
  mongodb:
    uri: ""
    database: "Job_auto"

# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file: "logs/job_automation.log"
  max_size: "10 MB"
  retention: "30 days"

# LLM Configuration - Gemini
llm:
  provider: "gemini"
  model: "gemini-1.5-flash"
  max_tokens: 3000
  temperature: 0.7
  caption_style: "professional"
  emoji_enabled: true
  hashtag_count: 7

# Image Generation Configuration
image_generation:
  enabled: true
  provider: "gemini"
  model: "gemini-pro-vision"
  style: "professional"
  size: "1024x1024"
  include_logo: true
  include_job_title: true
  include_company_name: true
  background_style: "clean"
